### ISSUE TITLE
1.21 stable libcontainers repo for centOS_8_Stream fails to build

### ISSUE THREAD

**Issue by rhrazdil** [cri-o/cri-o#4768]
cri-o 1.21 stable is missing repository for CentOS_8_Stream:
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21/
(As opposed to 1.20 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.20/)

IN OBS cri-o package for CentOS_8_Stream shows as unresolvable, apparently because [go-md2man failed to build](https://build.opensuse.org/package/live_build_log/devel:kubic:libcontainers:stable:cri-o:1.21/go-md2man/CentOS_8_Stream/x86_64):

https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable:cri-o:1.21

**Comment by haircommander** [comment]
I believe I've fixed it

**Comment by rhrazdil** [comment]
Hello @haircommander, thank you for your quick response.
Unfortunately, I'm still seeing the error. The last build attempt is from Sat Apr 17 01:44:22, which, as far as I can tell, should be after you pushed your update. Would you mind please taking another look?

**Comment by haircommander** [comment]
okay I confirmed I got a success this time, so it *should* be good :)

**Comment by rhrazdil** [comment]
Many thanks @haircommander! Sure enough, [CentOS_8_Stream](https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21/) is looking _shiny_ now. 
Closing :)
