### ISSUE TITLE
Provide packages for Ubuntu 22.04 Jammy Jellyfish

### ISSUE THREAD

**Issue by julian-alarcon** [cri-o/cri-o#5838]
### What happened?

Ubuntu 22.04 was [released the last April 22nd](https://ubuntu.com/blog/ubuntu-22-04-lts-released). 

I will like/need to have 22.04 should be added to the build!

Repo URL is returning a 404: http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/

OpenSuse's OSB already supports this version: https://build.opensuse.org/project/show/Ubuntu:22.04 (https://github.com/openSUSE/open-build-service/issues/12496 is still open but as you see it's already available to use in a project)

### What did you expect to happen?

Ubuntu repo for 22.04 should be available and able to download install from it.

### How can we reproduce it (as minimally and precisely as possible)?

No repo for 22.04 available in https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/ and in docs there is no reference (of course because it's still not available) https://github.com/cri-o/cri-o/blob/main/install.md#apt-based-operating-systems

### Anything else we need to know?

As Ubuntu 22.04 is a LTS version, it will have a long time support and probably is going to be a popular Distro to install use cri-o.

For now I was able to setup cri-o using the Ubuntu 20.04 packages available in here https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.23.2
Version:          1.23.2
GitCommit:        c0b2474b80fd0844b883729bda88961bed7b472b
GitTreeState:     clean
BuildDate:        2022-04-29T08:33:13Z
GoVersion:        go1.17.5
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        apparmor, exclude_graphdriver_devicemapper, containers_image_ostree_stub, seccomp
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl --version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-20T02:28:14Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
Linux carbonx1 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
</details>

**Comment by haircommander** [comment]
thanks for the heads up! I've attempted to add it to cri-o 1.23, 1.23.1, 1.22 and 1.21, let me know if there's another verison you'd like to see support for

**Comment by julian-alarcon** [comment]
I think that current supported versions are OK, and you already added them! (1.24 seems to be released today but I don't see this as a big hurry for now)

**Comment by haircommander** [comment]
yeah we plan on cutting cri-o 1.24.0 on friday (three days after kubernetes release :smiley: )

**Comment by gnomus** [comment]
Hello,

any Update on this?
http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/ unfortunatly still gives me a 404.

**Comment by haircommander** [comment]
ah you're looking at the root of the directory, what version of CRI-O are you trying to looking to use @gnomus

**Comment by carlosrmendes** [comment]
still no v1.24 neither for Ubuntu 22.04 nor for 20.04

**Comment by haircommander** [comment]
you can find the builds for 1.23 here https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.23/xUbuntu_22.04/

when I say "top level" I mean the cri-o projects don't show in the `stable` directory as they themselves are projects that contain subdirectories. it's an OBS thing, Not sure why. Anyhow, you can see all versions cri-o has supported here https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/ and there are a couple of releases that I've added support for Ubuntu 22.04

**Comment by gnomus** [comment]
According to https://github.com/cri-o/cri-o/blob/main/install.md#apt-based-operating-systems I need to execute (for example):
```
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key | gpg --dearmor -o /usr/share/keyrings/libcontainers-archive-keyring.gpg
```
That call does not work for 22.04

I am aware that there are Packages for 22.04 present somewhere on the Mirror.
But not in a way that allows me to follow the Install Instructions with `OS=xUbuntu_22.04`

So I just wanted to ask you to not only publish Packages for 22.04 but also update your documentation on it. (If the Process for 22.04 differs for some Reason)

Alternativly I would suggest that you also publish the Packages (and stuff like the `Release.key` the same way like for 20.04 so the Install Instructions work for 22.04.

**Comment by ComputerBaer** [comment]
@haircommander There were build errors, can you get those fixed too? Thank you!

**Comment by Jeansen** [comment]
There is also no Package for Debian. They are all excluded for 1.24
https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable:cri-o:1.24/cri-o

With 1.23 I can follow the main guide at https://cri-o.io/. But with 1.24 apt will not find the package cri-o (because it is not yet built).

**Comment by haircommander** [comment]
Okay  I believe I've fixed for 1.23. Were there any other versions that need fixing?

**Comment by Jeansen** [comment]
@haircommander I think you meant 1.24 ;-) and that works now. At least for me. :+1:

**Comment by ComputerBaer** [comment]
The top level repo for Ubuntu 22.04 is still missing `cri-o-runc` and more, because of failed go packages.

see https://build.opensuse.org/project/monitor/devel:kubic:libcontainers:stable?defaults=0&succeeded=1&failed=1&unresolvable=1&arch_x86_64=1&repo_xUbuntu_22_04=1

**Comment by haircommander** [comment]
Okay should be updated! are we good to close this?

**Comment by SriRamanujam** [comment]
Could you please have 1.21 and 1.22 fixed as well? Much appreciated!

**Comment by haircommander** [comment]
I think I've fixed it, should be available in an hour or so

**Comment by mythi** [comment]
We moved to 22.04 + cri-o but there's one issue with the packaging (not 22.04 specific): we also install `podman` which is now part of the distro itself so we get two versions of "containers-common" which try to install same files and apt fails:

```
dpkg: error processing archive /tmp/apt-dpkg-install-wp0xXX/58-containers-common_100%3a1-22_all.deb (--unpack):
 trying to overwrite '/etc/containers/policy.json', which is also in package golang-github-containers-common 0.44.4+ds1-1
```

**Comment by tomtom94** [comment]
Hey @mythi I am encountering the same issue 😂 
I have shoot on containers repositroy myself https://github.com/containers/buildah/issues/4012

**Comment by haircommander** [comment]
I've attempted an update for 1.24, if it works I will do the same for 1.23 and 1.22 :smiley:

**Comment by mythi** [comment]
> I've attempted an update for 1.24, if it works I will do the same for 1.23 and 1.22 smiley

I can confirm my use-case works: I managed to install `apt install cri-o cri-o-runc podman` using `OS=xUbuntu_22.04` and `VERSION=1.24`.

**Comment by tomtom94** [comment]
**It works fine with `VERSION=1.24` 🌱** so I am gonna use this version from now on 😂 

But still not working with `VERSION=1.23`

This is due to (if ever you wanna reproduce)
```
# Install cri-o
sudo apt-get update && sudo apt-get upgrade -y
export OS=xUbuntu_20.04
export VERSION=1.23
echo "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /" | sudo tee -a /etc/apt/sources.list.d/cri-0.list
curl -L http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/Release.key | sudo apt-key add -
echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /" | sudo tee -a /etc/apt/sources.list.d/libcontainers.list
sudo apt-get update
sudo apt-get install -y cri-o cri-o-runc podman buildah
```

```
dpkg: error processing archive /tmp/apt-dpkg-install-ViecMp/22-containers-common_100%3a1-22_all.deb (--unpack):
 trying to overwrite '/etc/containers/policy.json', which is also in package golang-github-containers-common 0.44.4+ds1-1
```

```
Errors were encountered while processing:
 /tmp/apt-dpkg-install-ViecMp/22-containers-common_100%3a1-22_all.deb
needrestart is being skipped since dpkg has failed
                                                  E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by mythi** [comment]
> But still not working with VERSION=1.23

@tomtom94 this is expected. the fix will be rolled out to other versions after we have confirmed the 1.24 fix works.

**Comment by haircommander** [comment]
1.23 should be updated now too! I believe we can close this, does anyone have any additional issues?

**Comment by jefflill** [comment]
I was just able to install v1.24 on Ubuntu 22.04, but the [installation instructions](https://github.com/cri-o/cri-o/blob/main/install.md) need a minor update:

- [ ] Add an **Operating System=Ubuntu 22.04 $OS=xUbuntu_22.04** row to the environment table for Ubuntu.

**Comment by jefflill** [comment]
**DONE:** https://github.com/cri-o/cri-o/pull/5909

**Comment by saschagrunert** [comment]
A friendly reminder that this issue had no activity for 30 days.

**Comment by jefflill** [comment]
I believe I've already signed the commit.

You know, you guys are making this really hard to make a one line documentation change.  How about one of you make this change yourselves?

**Comment by gmarkey** [comment]
Hi,

There are no 1.21 builds for Ubuntu 22.04

**Comment by haircommander** [comment]
with 1.24 release, 1.21 is out of support. I attempted to add it but there was a build failure. I'm afraid I'm too spread thin to take a look right now
