### ISSUE TITLE
ReopenContainerLog hangs for containers in a stopping state

### ISSUE THREAD

**Issue by dlmather** [cri-o/cri-o#6297]
### What happened?

We're using CRIO on our Kubernetes clusters. We have a number of cases with Pods with an especially long termination grace period (that also happen to emit a lot of logs). We've noticed that after a period of time, we end up in a bad state with the log files of these terminating pods (post log rotation). Specifically we see an error like the following:

```
 k logs worker-live-5cd566c94b-z82nq worker
failed to try resolving symlinks in path "/var/log/pods/gcp-us-east1-vop1_worker-live-5cd566c94b-z82nq_e08e60cf-4557-4a5f-9d83-3188d7c4808d/worker/0.log": lstat /var/log/pods/gcp-us-east1-vop1_worker-live-5cd566c94b-z82nq_e08e60cf-4557-4a5f-9d83-3188d7c4808d/worker/0.log: no such file or directory
```

We believe this issue is due to the fact that when the Kubelet tries to rotate the container logs it will call for ContainerStatus: https://github.com/kubernetes/kubernetes/blob/acc64759f5fc434f325756f438f676daa3f0ed28/pkg/kubelet/logs/container_log_manager.go#L231 and this call will error/timeout for Containers that are being stopped in CRIO due to the lock on container state, as read here: https://github.com/cri-o/cri-o/blob/2c43fb8a34e1cf59266e2f9a903e9ce88bf4c8ef/server/container_status.go#L125.

### What did you expect to happen?

Containers that are being shutdown will be able to have their log files correctly rotated. We'd expect the Kubelet to get sufficient information from the ContainerStatus.

### How can we reproduce it (as minimally and precisely as possible)?

A container that produces a large volume of logs sufficient to trigger a log rotation while in the shutting down state should demonstrate the problem.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio --version
crio version 1.23.3
Version:          1.23.3
GitCommit:        2cf9dbf1a447d25931008c1815de407d9e5749f7
GitTreeState:     clean
BuildDate:        2022-08-30T09:37:43Z
GoVersion:        go1.17.5
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        seccomp, selinux
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl --version
# paste output here
kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:57:43Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
# cluster is also 1.23.8
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
 cat /etc/os-release
NAME=Fedora
VERSION="34.20211031.3.0 (CoreOS)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora CoreOS 34.20211031.3.0"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='34.20211031.3.0'
DEFAULT_HOSTNAME=localhost
$ uname -a
# paste output here
Linux worker-live-n1-highcpu-32-20220831-1661879452-cd23b1cb6e-zp4ds 5.14.14-200.fc34.x86_64 #1 SMP Wed Oct 20 16:15:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
GCP (but not GKE).
</details>

**Comment by dlmather** [comment]
Hmm, you're right... let me try to cook up a simple Pod recipe that reproduces the issue.

**Comment by dlmather** [comment]
Cool, cooked something up here, maybe not the cleanest or most simple way but worked for me to reproduce:
```
---
kind: Pod
apiVersion: v1
metadata:
  name: big-log-test
  namespace: default
spec:
  volumes:
  - name: script
    configMap:
      name: big-log-script
  containers:
  - name: big-log
    image: alpine:latest
    command:
    - /bin/sh
    - /etc/mux/big-log/exec.sh
    resources: {}
    volumeMounts:
    - name: script
      mountPath: /etc/mux/big-log
  terminationGracePeriodSeconds: 600
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: big-log-script
  namespace: default
data:
  exec.sh: |
    #!/bin/sh

    set -ou

    trap 'echo stopping; cat 1gb-file | base64; cat 1gb-file | base64; sleep 300; exit' SIGTERM
    dd if=/dev/zero of=1gb-file bs=100000 count=10000

    function log_out() {
      while true
      do
          cat 1gb-file | base64
          sleep 10
      done
    }

    log_out
```
ran a `k delete pod big-log-test` and after allowing a bit of time for rotation to kick in (couple minutes):
```
 k logs big-log-test
failed to try resolving symlinks in path "/var/log/pods/default_big-log-test_cc24014c-90c7-4841-9304-19f0ccbc2c50/big-log/0.log": lstat /var/log/pods/default_big-log-test_cc24014c-90c7-4841-9304-19f0ccbc2c50/big-log/0.log: no such file or directory
```
on the host:
```
[root@node-n2-standard-16-20220831-1661879452-1cedf1ca60-9kf54 big-log]# pwd
/var/log/pods/default_big-log-test_cc24014c-90c7-4841-9304-19f0ccbc2c50/big-log
[root@node-n2-standard-16-20220831-1661879452-1cedf1ca60-9kf54 big-log]# ls -lh
total 484M
-rw-r--r--. 1 root root 1.7M Oct 12 21:12 0.log.20221012-211148.gz
-rw-r--r--. 1 root root 5.0M Oct 12 21:12 0.log.20221012-211201.gz
-rw-------. 1 root root 477M Oct 12 21:12 0.log.20221012-211726
```

**Comment by dlmather** [comment]
Kubelet should be using default setting around rotation as well, for the record.

**Comment by haircommander** [comment]
@dlmather a little late, but I think this was fixed in https://github.com/cri-o/cri-o/pull/6925, would you be able to test it out and see?

**Comment by Ezetowers** [comment]
Hi @haircommander. We have hit this bug too. Our pods do not rotate their logs in Terminating state. I have installed crio 1.25.4 and the problem is still there. I attach a stacktrace of crio under these conditions [crio-goroutine-stacks-2023-08-28T210222Z.log](https://github.com/cri-o/cri-o/files/12470052/crio-goroutine-stacks-2023-08-28T210222Z.log). Let me know if you need anything else to understand what is going on here

## Crio and Kubernetes versions of the test
```
[root@yul1-r11-u13 efeyuk]# crio --version
crio version 1.25.4
Version:        1.25.4
GitCommit:      unknown
GitCommitDate:  unknown
GitTreeState:   clean
BuildDate:      2023-08-10T08:50:26Z
GoVersion:      go1.19
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:
  rpm_crashtraceback
  exclude_graphdriver_btrfs
  btrfs_noversion
  exclude_graphdriver_devicemapper
  libdm_no_deferred_remove
  seccomp
  containers_image_openpgp
LDFlags:          -X github.com/cri-o/cri-o/internal/pkg/criocli.DefaultsPath= -X  github.com/cri-o/cri-o/internal/version.buildDate=2023-08-10T08:50:26Z -X  github.com/cri-o/cri-o/internal/version.gitCommit=3ad059f673902a0b502da5e9ec80714df08f3f4e -X  github.com/cri-o/cri-o/internal/version.version=1.25.4 -X  github.com/cri-o/cri-o/internal/version.gitTreeState=clean  -B 0x0ae0f03614d4cdbdf46118d31839208bbeb1c635 -extldflags '-Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' -compressdwarf=false
SeccompEnabled:   true
AppArmorEnabled:  false
Dependencies:

[root@yul1-r11-u13 efeyuk]#

```
~ k8s(yul1) kubectl --context=yul1 version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.7", GitCommit:"723bcdb232300aaf5e147ff19b4df7ec8a20278d", GitTreeState:"clean", BuildDate:"2023-02-22T13:58:23Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
~ k8s(yul1)
```
```

**Comment by dlmather** [comment]
> @dlmather a little late, but I think this was fixed in #6925, would you be able to test it out and see?

Sorry, I'm no longer working where I was and doing have access to that cri-o setup as such and can't really help out testing :(  Best of luck!

**Comment by audrey-mux** [comment]
I DO have access to the environment and I tested this out using cri-o 1.25.4. I fired up the pod test given by @dlmather, let the log create, then terminated the pod. 

I was able to tail the log `k logs -f big-log-test` while the pod was `Terminating` right up to the point where it was actually killed.

**Comment by haircommander** [comment]
sounds to me that this can be closed, do you agree @audrey-mux
