### ISSUE TITLE
Add blog to crio.io

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#7276]
Goal is to have blogging capabilities in crio.io, probably by having a great integration into GitHub.

**Comment by siddharth-sable** [comment]
Hey @saschagrunert, Can I work on this?

**Comment by saschagrunert** [comment]
@siddharth-sable sure! The website repository is there: https://github.com/cri-o/cri-o.io

We may want to elaborate something like [Hugo](https://github.com/gohugoio/hugo), but we're open for suggestions.

**Comment by siddharth-sable** [comment]
Thank you

**Comment by siddharth-sable** [comment]
Hello @saschagrunert we can use hugo, but it would be complex to manage two static site generators into a single project. Instead we can just configure jekyll for blogging. I would look further what all changes we need to make into the project.

Please suggest we should go with hugo or add blogging to jekyll?

**Comment by saschagrunert** [comment]
@siddharth-sable I also prefer having only one site generator. If jekyll works greatly with blogs then I'm happy to give that one a try :)

**Comment by siddharth-sable** [comment]
Okay, will proceed with jekyll

**Comment by siddharth-sable** [comment]
Hello @saschagrunert , I did try adding blogs. Please take a look.
Whenever someone visits /blog, we had redirection to medium blog. I changed it.

https://github.com/cri-o/cri-o/assets/66620788/d2692e65-c4ab-425a-8efb-b854ef0fea46

**I had few queries:**

I did notice we have some old blogs on medium. Do we have any plan to bring them on jekyll? or they are fine there

If anyone wants to add a blog they will create their post in _posts folder, also will add themselves as an author in _authors folder. Do I need to mention these steps somewhere?

Where do we need to mention about blogs on the main page?

**Comment by saschagrunert** [comment]
@siddharth-sable thank you, this looks like a great start!

> I did notice we have some old blogs on medium. Do we have any plan to bring them on jekyll?

Let's create a follow-up issue for that. We can create a dedicated first blog post linking to previous articles.

> If anyone wants to add a blog they will create their post in _posts folder, also will add themselves as an author in _authors folder. Do I need to mention these steps somewhere?

Yes, having this part of the project README.md would be fine.

> Where do we need to mention about blogs on the main page?

How to reference them? Let's figure it out at some later point.

**Comment by siddharth-sable** [comment]
> Let's create a follow-up issue for that. We can create a dedicated first blog post linking to previous articles.

Okay.

> Yes, having this part of the project README.md would be fine.

I will add it.

> How to reference them? Let's figure it out at some later point.

Cool.

**Comment by amitamrutiya2210** [comment]
Hey @saschagrunert, @haircommander, if no one is currently working on this issue, I'd like to give it a try.

**Comment by siddharth-sable** [comment]
Hey @amitamrutiya2210 the issue has been fixed. I am also waiting for further update from the maintainers.

**Comment by amitamrutiya2210** [comment]
No worries @siddharth-sable, keep up the good work. I just thought this issue had been inactive, which is why I asked.

**Comment by saschagrunert** [comment]
Hey folks, If I did not miss anything then the blog is still not available yet on cri-o.io :)

**Comment by saschagrunert** [comment]
I'm not sure we actually need this one, we can host blog posts on the official CNCF website as well.
